version: 2.1


orbs:
  codecov: codecov/codecov@6.0.0


jobs:
    check_code_quality:
        docker:
            - image: cimg/python:3.14
        steps:
            - checkout
            - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "uv.lock" }}
            - run:
                name: Install uv
                command: pip install --user uv==0.11.28
            - run:
                name: Install dependencies
                command: uv sync --frozen --all-groups --all-extras
            - save_cache:
                paths:
                  - ~/.cache/pip
                  - ~/.cache/uv
                key: v1-dependencies-{{ checksum "uv.lock" }}
            - run: 
                name: Run quality tests
                command: make quality

    run_tests:
        docker:
            - image: cimg/python:3.14
        steps:
            - checkout
            - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "uv.lock" }}
            - run:
                name: Install uv
                command: pip install --user uv==0.11.28
            - run:
                name: Install dependencies
                command: uv sync --frozen --all-groups --all-extras
            - save_cache:
                paths:
                  - ~/.cache/pip
                  - ~/.cache/uv
                key: v1-dependencies-{{ checksum "uv.lock" }}
            - run:
                name: Run tests
                command: make test-ci
            - run:
                name: Run static type checking
                command: make types
            - codecov/upload:
                files: coverage.xml
                disable_search: true
                fail_on_error: true


workflows:
    build_and_test:
        jobs:
            - check_code_quality
            - run_tests
